### ISSUE TITLE
Ability to search for students

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#35]
As admin, I'm not sure how to find students' profiles except to sign in as them and copy their profile url and sign back out.

**Comment by awesomeisfree** [comment]
Well we could make the launchpad search include the author, but that wouldn't include peeps who've never made a untutorial.
You could also go to their class. The profiles there are all links.
Otherwise, this sounds like a new page. Can you tell me all that you want on it? Just a profile search? It might be good to combine a few new feature requests into a new page.

**Comment by madduccino** [comment]
The class page might be a good hub for now while we figure out what is needed, but I'd like to be able to click through to their profile I think.
