### ISSUE TITLE
Launchpad filters are counterintuitive

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#39]
Students think they should click Scratch to see Scratch untutorials. Instead, when you click Scratch, Scratch untuts are filtered out.

**Comment by madduccino** [comment]
I like how this works: https://www.education.com/games/second-grade/

Would love the ability to add more categories in addition to Levels, potentially.

**Comment by awesomeisfree** [comment]
the launchpad at that link works the same way as our site. At that link is a bubble called second grade and when you click it, second grade is removed from the filter. And when there are no filters it shows all. We work the same way. The difference is that, we load in with three filters already there (scratch, web, and woof) so when they click scratch, web and woof are still filtering. If we just load in with no filters (or one filter, but you'd have to pick which) it'll be exactly the same. I think you actually already figured this out, because you commented out woof and web in the most recent version. Would you like me to do set it to zero filters?

Regarding categories; we already have the backend for it. Untuts have categories. There just isn't any way to filter by them. We can do that too.

**Comment by madduccino** [comment]
Oh yeah, it _does_ work the same. I didn't even notice the bubble on top. What I noticed was the side menu which made it clear to me what was selected. 

In our site, instead of the "select" menu we have now could we make them links that show/hide? I will also add the "x" to the bubbles so it's clear clicking means closing. 

Yeah, I made the filter just Scratch for now. Probably the way to go.

Yes, definitely want to filter for levels and categories. Will "Add Category" be added to New Untutorial?
